name: cqlbr_db2
description: CQLBr Framework for Dart/Flutter (DB2)
version: 0.0.2
homepage: https://github.com/isaquepinheiro
publish_to: 'none'

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cqlbr_core:
    path: ../cqlbr_core
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0