name: cqlbr_firestore
description: CQLBr Framework for Dart/Flutter (firestore)
version: 0.0.1
homepage: https://github.com/isaquepinheiro
publish_to: 'none'

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cqlbr_core:
    path: ../cqlbr_core
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  fake_cloud_firestore: ^2.4.1+1