name: dart_cqlbr_core
description: CQLBr Framwork for Dart/Flutter (core)
version: 0.0.1
homepage: https://github.com/isaquepinheiro

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0