name: dart_cqlbr_db2
description: CQLBr Framework for Dart/Flutter (DB2)
version: 0.0.2
homepage: https://github.com/isaquepinheiro
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_cqlbr_core:
    path: ../dart_cqlbr_core
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0